### ISSUE TITLE
静态编译问题

### ISSUE THREAD

**Issue by jm-observer** [losfair/smr#4]
你好！最近重装了电脑，然后这个库的静态编译（x86_64-unknown-linux-musl）的程序就会报错，请问知道是哪里有问题吗？求速回：
```
thread '<unnamed>' panicked at 'process manager crashed', /home/jmhuang/git/smr/src/pm.rs:123:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to initialize worker manager', examples/check.rs:57:6
```
代码：
```
use anyhow::Result;
use async_trait::async_trait;
use parking_lot::Mutex;
use serde::{Deserialize, Serialize};
use smr::pm::{pm_start, PmHandle};
use smr::scheduler::Scheduler;
use smr::types::{BaseRequest, Request, Response};

#[derive(Serialize, Deserialize, Debug)]
struct EchoReq {
  x: Vec<u8>,
}

#[derive(Serialize, Deserialize, Debug)]
struct EchoRes {
  x: Vec<u8>,
}

impl BaseRequest for EchoReq {
  type Res = EchoRes;
  type InitData = ();
  type Context = ();
}

#[async_trait(?Send)]
impl Request for EchoReq {
  async fn handle(self, _: &'static ()) -> Result<Self::Res> {
    Ok(EchoRes { x: self.x })
  }

  async fn init(_: ()) -> &'static () {
    &()
  }
}

impl Response for EchoRes {}

#[ctor::ctor]
static PM: Mutex<PmHandle<EchoReq>> = Mutex::new(
  #[allow(unused_unsafe)]
  unsafe {
    pm_start()
  },
);

fn main() {
  let pm = PM.lock().clone();
  let rt = tokio::runtime::Builder::new_current_thread()
    .enable_all()
    .build()
    .unwrap();
  let sched = rt.block_on(async { Scheduler::<u64, _>::new(pm) });
  let appid = 66u64;
  let mut buf = vec![0u8; 16];
  let worker = rt
    .block_on(Scheduler::get_worker(&sched, &0u64, || ()))
    .unwrap();
  let res = rt
    .block_on(worker.invoke(EchoReq { x: buf.clone() }))
    .unwrap();
  println!("{:?}", res);
  assert_eq!(res.x, buf);
}

```

**Comment by jm-observer** [comment]
进一步定义，发现是PmHandle发送WorkerInit的问题。当把WorkerInit里面的通道字段去掉，更改成如i32的字段时，就不会报错。

**Comment by losfair** [comment]
试试在 main 里初始化 PM 而不是用 `ctor` 初始化？全局 constructor 执行的时候进程环境不一定完整

**Comment by jm-observer** [comment]
已经定位到ipc-channel，也已经提交了issue：https://github.com/servo/ipc-channel/issues/296
